### ISSUE TITLE
Channel Activity Detection

### ISSUE THREAD

**Issue by gmsotavio** [CongducPham/LowCostLoRaGw#14]
Dear C. Pham.

Why the method `CarrierSense()` implements the Channel Activity Detection (CAD) if the frequency hopping feature has not been implemented? The RSSI measurement before send is not enough in order to check de activity of the channel? Could you clarify me. Thanks in advance.

Gomes, O.A.

**Comment by CongducPham** [comment]
Dear Otavio,

CAD tries to detect specific radio activity of LoRa modulation. So a 
carrier sense mechanism must at least use CAD. However, as CAD may not 
detect all transmission, especially when the preamble has been already 
sent, we tries to increase the reliability of carrier sense with RSSI 
reading. You must know that carrier sense in long-range transmission 
such as LoRa is far from being 100% reliable. So our proposed mechanism 
is probably not 100% reliable neither. We are still studying which 
improvements can be done.

regards,

Le 18/06/16 23:38, Otavio Augusto Gomes a écrit :
>
> Dear C. Pham.
>
> Why the method |CarrierSense()| implements the Channel Activity 
> Detection (CAD) if the frequency hopping feature has not been 
> implemented? The RSSI measurement before send is not enough in order 
> to check de activity of the channel? Could you clarify me. Thanks in 
> advance.
>
> Gomes, O.A.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/CongducPham/LowCostLoRaGw/issues/14>, or mute the 
> thread 
> <https://github.com/notifications/unsubscribe/ABNENxzazJB-hitr1_Og42xYQdGvSZJQks5qNGVogaJpZM4I5Cel>.
>

C. Pham.


-- 
|------------ Congduc PHAM - Professor --------------------------|
|  LIUPPA - Equipe T2I              |         U.P.P.A. Pau       |
|  http://liuppa.univ-pau.fr/       |   http://www.univ-pau.fr   |
|----------------------------------------------------------------|
|UPPA, LIUPPA laboratory, UFR Sciences et Techniques             |
|Avenue de l'Université - BP 1155                                |
|64013 PAU CEDEX, FRANCE                                         |
|                                                                |
|phone:  [33] (0) 5 59 40 75 94                                  |
|fax:    [33] (0) 5 59 40 76 54                                  |
|Congduc.Pham@univ-pau.fr       http://www.univ-pau.fr/~cpham    |
|----------------------------------------------------------------|
