### ISSUE TITLE
Error Adafruit Feather 32u4.

### ISSUE THREAD

**Issue by miryamparedes** [CongducPham/LowCostLoRaGw#156]
Hello. I am using an Adafruit Feather 32u4 board and when trying to compile the Arduino_Lora_Ping_Pong I get this message error:
exit status 1
Error compiling for board Adafruit Feather 32u4.

Please could you let me know what could be the problem? Thank you.

**Comment by CongducPham** [comment]
Well, I don't have this issue. What is the version of the adafruit lib you have? I have the latest one, 1.4.9, and it compiles without error.

**Comment by miryamparedes** [comment]
I am using that version as well. I have no idea what is wrong. Do you have any idea? Thank you. 

![adafruit](https://user-images.githubusercontent.com/32674364/33310317-79bf7a22-d421-11e7-8e72-edf00d741b14.png)

**Comment by CongducPham** [comment]
Maybe you are missing a lib. Please give more details on the error message.

**Comment by ethicstechOSS** [comment]
@miryamparades Most probably you forget to install the SX1272 library on your arduino IDE. Just installing the Adafruit package is not enough to compile a LoRa program successfully.

**Comment by miryamparedes** [comment]
Dear all, thank you for your help. I made a mistake when installing the libraries in the wrong file.
