### ISSUE TITLE
[ENHANCEMENT] LoRaWAN/Packet Forwader support

### ISSUE THREAD

**Issue by ethicstechOSS** [CongducPham/LowCostLoRaGw#165]
Hi,
Is there any plan to support LoRaWAN & Packet forwarder (to support multichannel gateway) on this project?. 

TIA,
Prakash

**Comment by CongducPham** [comment]
No, we are not going to support multichannel gateway nor traditional packet forwarder. We may support connection to a lorawan server such as TTN for demonstration purposes.

**Comment by ethicstechOSS** [comment]
Thanks for the info.
