### ISSUE TITLE
Changes made in lora gateway files using terminal is not reflecting on browser UI

### ISSUE THREAD

**Issue by Ram-Murali** [CongducPham/LowCostLoRaGw#166]
Hi, 
    I'm using Raspberry pi Low cost lora gateway.On terminal my gateway is working good.But the problem is whatever changes made in gateway files is not reflecting on browser UI.
     I'm currently working on customizing gateway UI with the help of files in link shown below:
https://github.com/CongducPham/LowCostLoRaGw/tree/master/gw_full_latest/gw_web_admin/admin

Any help would be appreciated
Thanks in Advance

**Comment by CongducPham** [comment]
That strange. Try install the latest version of the web interface. If already done, then I don't actually see why changes are not reflecting on the web interface. I've tested and it works for me.

**Comment by Ram-Murali** [comment]
thanks for your support.
