### ISSUE TITLE
No downlink log after having built it

### ISSUE THREAD

**Issue by franclr** [CongducPham/LowCostLoRaGw#178]
Hi,

I am trying to use the downlink feature to send data to a device.

I followed your tutorial of the following page but it does not work in my case: https://github.com/CongducPham/LowCostLoRaGw/blob/master/gw_full_latest/README-downlink.md 

As indicated, I used 

> make lora_gateway_pi2_downlink

When I start the gateway, I don't have any log concerning "post downlink".

I am using RPI3 B.

Any idea on how to save it ?
Thanks a lot !

**Comment by CongducPham** [comment]
You have to set in gateway_conf.json the downlink timer to a value greater than 0. 600 means 600s so every 10mins.

regards,

**Comment by franclr** [comment]
Thank you, working now !
