### ISSUE TITLE
Value error : Expecting delimiter :

### ISSUE THREAD

**Issue by aniket1002** [CongducPham/LowCostLoRaGw#205]
Hello @CongducPham sir,
I'm getting this on my gateway : 

![send 1](https://user-images.githubusercontent.com/35869599/41038520-174ab8ce-69b4-11e8-9bc8-ae33688a8ae9.jpg)
I've tried rebooting the gateway and replacing the post_processing_gw.py
How can I solve this issue?
Looking forward to your response..
Regards

**Comment by CongducPham** [comment]
Check format of the json file that you've modified.

**Comment by aniket1002** [comment]
Thanks sir for a prompt reply..
It worked ! 
Regards
