### ISSUE TITLE
mqtt with username and password

### ISSUE THREAD

**Issue by htcheroportugal** [CongducPham/LowCostLoRaGw#212]
hello, my broker mqtt had username and password, how can use my private broker with this gateway?

**Comment by CongducPham** [comment]
CloudMQTT.py uses mosquitto_pub, just add your credentials using options

**Comment by htcheroportugal** [comment]
@CongducPham sorry ask you again, but can you show me how can to do that? i dont undersand what you say.

**Comment by htcheroportugal** [comment]
@congducPham if nomenclatures=='':
	cmd = 'mosquitto_pub -u username -P password -h '+key_MQTT.MQTT_server+' -t '+data[0]+'/'+data[1]+'/'+src+' -m \"'+data[i+2]+'\"'
else:
	cmd = 'mosquitto_pub -u username -P password -h '+key_MQTT.MQTT_server+' -t '+data[0]+'/'+data[1]+'/'+src+'/'+nomenclatures[i]+' -m \"'+data[i+2]+'\"'

That is correct?

**Comment by CongducPham** [comment]
Looks good.

**Comment by htcheroportugal** [comment]
@CongducPham  i tried with:

![image](https://user-images.githubusercontent.com/24639142/41875298-5ff30a3c-78c2-11e8-9657-e450ca90871c.png)

But not sucess.my broker is 192.168.1.855

**Comment by CongducPham** [comment]
I believe you replace username and password with your actual user name and password right?

**Comment by htcheroportugal** [comment]
no, sorry i forgot that...  i replaced it and now it works.. thanks again for your support.
