### ISSUE TITLE
Link to SD image in README is broken

### ISSUE THREAD

**Issue by periap6** [CongducPham/LowCostLoRaGw#222]
Hi there, it seems the university of pau personal pages website is down, any chance to have the zipped SD card image (raspberrypi-jessie-WAZIUP-demo.dmg.zip) hosted on github or another cloud (dropbox, drive)? Thank you!

**Comment by malishahi** [comment]
the same for me. I cannot download.

**Comment by CongducPham** [comment]
The server is up again. regards,

**Comment by periap6** [comment]
Amazing, thanks!

**Comment by antonmeyer** [comment]
10.2.1019 down again?

**Comment by CongducPham** [comment]
A power shortage shutdown my computer which provides Internet to my Raspberry. Now should be ok.
regards,

**Comment by omaralaoui1999** [comment]
14/04/2021 down again ?
