### ISSUE TITLE
Support for ET32-TTL-100 module

### ISSUE THREAD

**Issue by Philippe-Collignon** [CongducPham/LowCostLoRaGw#231]
Hello,

First thanks for nice work !

Is ET32-TTL-100 module supported ? 

It is based on SX1278 and has M0,M1,RXD,TXD,GND and VCC pins :
https://fr.aliexpress.com/item/Free-shipping-CDSENET-E32-TTL-1W-7500m-1W-SX1278-SX1276-LoRa-433MHz-long-range-rf-transceiver/32791508935.html?spm=a2g0s.9042311.0.0.40696c37KNemfu

Unfortunatly it has UART communication

user manual is here : http://www.cdebyte.com/en/data-download.aspx?page=3&id=214&cid=31

Is it compatible with your project ? 

Thanks in advance.

**Comment by Philippe-Collignon** [comment]
Unfortunately it has UART communication

**Comment by CongducPham** [comment]
Yes, I was going to answer, we do not support UART.
regards,
