### ISSUE TITLE
number of enabled clouds is 0

### ISSUE THREAD

**Issue by Roedyroll** [CongducPham/LowCostLoRaGw#257]
When i set the all clouds to false but the "WAZIUP Orion cloud new API" to true i get number of enabled clouds is 0. I switched form old and new. 
Does have some one a solution?

**Comment by CongducPham** [comment]
did you reboot?

**Comment by Roedyroll** [comment]
Yeah i did, i thought it had to do with the LoRaWAN mode. but never the less i still can't send the data to the cloud.
the mode is set to 1
frequency to 869.5
PA_BOOST enabled 

it looks like it has to do with the encrypted clouds

**Comment by Roedyroll** [comment]
okay, i was in the ballpark. i needed to set raw to false and aes to true.
