### ISSUE TITLE
compability with nucleo073rz and lora sx1272 shield

### ISSUE THREAD

**Issue by Arcanum7** [CongducPham/LowCostLoRaGw#263]
I have nucleo073rz and lora sx1272 shield.
I want to have a lora gateway based on these boards.
I had loaded your sketch in stm32l073rz nucleo board but everehing a had got in terminal is 
15:28:08.981> SX1272 detected, starting
15:28:09.230> ...
15:28:09.417> ^$**********Power ON: state 0
15:28:09.417> ^$LoRa mode 1
15:28:10.229> ^$Setting mode: state 0
15:28:10.416> ^$Channel CH_10_868: state 0
15:28:10.541> ^$Set LoRa power dBm to 14
15:28:10.541> ^$Power: state 0
15:28:10.541> ^$Get Preamble Length: state 0
15:28:10.541> ^$Preamble Length: 8
15:28:10.541> ^$LoRa addr 1: state 0
15:28:10.603> ^$SX1272/76 configured as LR-BS. Waiting RF input for transparent RF-serial bridge^$Default sync word: 0x12
15:28:11.601> ^$Low-level gw status ON
and thats all.

**Comment by CongducPham** [comment]
Did you sent anything with another node? BTW, I didn't know that Nucleo boards can be supported in Arduino IDE actually, so good to know.

**Comment by Arcanum7** [comment]
Nucleo boards are supported. Blink is work fine.
And I sent a lot of frames by another end-node device, and rcv it by IOTVega-GateWay (proffesional gateway)

**Comment by CongducPham** [comment]
So I guess the other end-node is sending in LoRaWAN mode right?

If you want the loragateway program to run in LoRaWAN mode, you need to set loraMode to 11 which will set the listening frequency to 868.1MHz and set the sync word to 0x34.

Using an Arduino-like gateway is not the main purpose of this code. It is intended to rbe un and configured by higher layers on a Raspberry for instance.

**Comment by Arcanum7** [comment]
>>So I guess the other end-node is sending in LoRaWAN mode right?
yes

>>If you want the loragateway program to run in LoRaWAN mode, you need to set loraMode to 11 which will set the listening frequency to 868.1MHz and set the sync word to 0x34.

15:56:48.067> SX1272 detected, starting
15:56:48.317> ...
15:56:48.567> ^$**********Power ON: state 0
15:56:48.567> ^$LoRa mode 1
15:56:49.315> ^$Setting mode: state 0
15:56:49.565> ^$Channel CH_10_868: state 0
15:56:49.627> ^$Set LoRa power dBm to 14
15:56:49.627> ^$Power: state 0
15:56:49.627> ^$Get Preamble Length: state 0
15:56:49.627> ^$Preamble Length: 8
15:56:49.690> ^$LoRa addr 1: state 0
15:56:49.690> ^$SX1272/76 configured as LR-BS. Waiting RF input for transparent RF-serial bridge^$Default sync word: 0x12
15:57:11.468> Rcv serial: /@M11
15:57:11.468> ^$Parsing command^$/@M11
15:57:11.468> ^$Set LoRa mode to 11
15:57:12.155> ** Using sync word of 0x34
15:57:12.280> ^$LoRa mode: state 0
15:57:12.280> Get Preamble Length: state 0
15:57:12.280> Preamble Length: 8
15:58:04.041> Rcv serial: /@SF12
15:58:04.104> ^$Parsing command^$/@SF12
15:58:04.104> ^$set SF: 12
15:58:04.166> ^$set SF: state 0

no reaction

>>Using an Arduino-like gateway is not the main purpose of this code. It is intended to rbe un and configured by higher layers on a Raspberry for instance.

this is first step - get something frames to understand "does it work?"
pythin code is next stage

**Comment by CongducPham** [comment]
You have to set it in the code. 

https://github.com/CongducPham/LowCostLoRaGw/blob/f7727c733ed3df6817be3ff61299569d0576ac25/Arduino/Arduino_LoRa_Gateway/Arduino_LoRa_Gateway.ino#L370

If you are using remote command, then you have to set the frequency as well to ch 18.

**Comment by CongducPham** [comment]
What is the other end-node you are using to send message?

**Comment by CongducPham** [comment]
Great. I believe it is a LoRaWAN encrypted packet.

**Comment by Arcanum7** [comment]
>> What is the other end-node you are using to send message?
same boards: nucleoL073RZ +sx1272 shield
firmware is my own based LoRaLib by semtech. wroten in atollic true stuido

**Comment by Arcanum7** [comment]
damn! i recive only 3 frames and nothing esle more

**Comment by Arcanum7** [comment]
no. it doesn't work again.

**Comment by Arcanum7** [comment]
oh, wow. it rcv again smth.
i leave rcv on for night and set frame sending every 5 min.

**Comment by Arcanum7** [comment]
>>Unless you try to guess what will be the next channel, but it is aonly working with one sender node.

is it possible?


sx1272 datasheet says that it can listen several shanels.
can you add this featuter, please?

**Comment by CongducPham** [comment]
sx1272 is single channel, at a time.

We will not implement channel hopping. In case several channel is required, we use the traditional SX1301 concentrator. regards,
