### ISSUE TITLE
how to config pin of SPI

### ISSUE THREAD

**Issue by dekpri** [CongducPham/LowCostLoRaGw#272]
i Have buy rfm95 Shield from M2M
the pin is

For M2M Shop RPI Shiled
  "pin_nss": 6,
  "pin_dio0": 7,
  "pin_rst": 0

but i think in this project same as LoRasPi Shield
  "pin_nss": 8,
  "pin_dio0": 6,
  "pin_rst": 3,
  "pin_led1":4

how can i config to use my shield to work with this project thank

**Comment by CongducPham** [comment]
The important pin is nss and then maybe rst. look in SX1272.h for the definition of these pins, then change them accordingly.

regards,
