### ISSUE TITLE
 ‘time_buffer’ was not declared in this scope

### ISSUE THREAD

**Issue by sheggy012** [CongducPham/LowCostLoRaGw#275]
Hey, 
the Readme says: 
downlink.txt file can be renamed as downlink-backup-2020-01-20T13:42:23.txt (with the current date indicated) if lora_gateway is compiled with #define KEEP_DOWNLINK_BACKUP_FILE

But when I try to compile with this setting in lora_gateway.cpp, it gives me the following error.
```
pi@raspberrypi:~/lora_gateway $ sudo nano lora_gateway.cpp
pi@raspberrypi:~/lora_gateway $ make
g++ -DPABOOST -DMAX_DBM=14 -DBAND868 -DGETOPT_ISSUE -c lora_gateway.cpp -o lora_gateway.o
lora_gateway.cpp: In function ‘void loop()’:
lora_gateway.cpp:1015:80: error: ‘time_buffer’ was not declared in this scope
     sprintf(tmp_c, "mv downlink/downlink.txt downlink/downlink-backup-%s.txt", time_buffer);
                                                                                ^~~~~~~~~~~
lora_gateway.cpp:1015:80: note: suggested alternative: ‘setbuffer’
     sprintf(tmp_c, "mv downlink/downlink.txt downlink/downlink-backup-%s.txt", time_buffer);
                                                                                ^~~~~~~~~~~
                                                                                setbuffer

```
Where can I set the time_buffer?
Regards

**Comment by CongducPham** [comment]
Sorry, due that it is in a conditional compilation block, I didn't check consistency with recent changes. You can use instead time_str and then the name would be in the following format:

downlink-backup-2020-03-26T14:57:51.971208.txt

regards,
