### ISSUE TITLE
Stm32L072 + Sx1272 Uart rcv of packets

### ISSUE THREAD

**Issue by Arcanum7** [CongducPham/LowCostLoRaGw#278]
Hi! I have only notebook with ubuntu 16.04 lts and no RaspPi.
I can rcv messages by usb CDC from Stm32L072 + Sx1272 (nucleo L073 and sx1272 shield) only.
How to get  start gateway software *.py scripts in this case?

**Comment by CongducPham** [comment]
Hi, you can use the STM programmed with the Arduino_LoRa_Gateway sketch (https://github.com/CongducPham/LowCostLoRaGw/tree/master/Arduino/Arduino_LoRa_Gateway). Then use it as a radio bridge as described here: http://cpham.perso.univ-pau.fr/LORA/RPIgateway.html, look at section "7. Tools for testing & build a LoRa gateway for on-the-go tests"

hope that helps, regards,

**Comment by Arcanum7** [comment]
it help.
BUT:
1) it need python2  with installed pyserial and requests modules - nowhere it write
2) how to log (python ./log_gw.py) without Dropbox files and folders need?
3) it starts with sudo only
`sudo python 38400SerialToStdout.py /dev/ttyS0 | sudo python ./post_processing_gw.py
`

**Comment by CongducPham** [comment]
You can change the log folder in log_gw.py if it is necessary

**Comment by Arcanum7** [comment]
ok, i'll try
`python 38400SerialToStdout.py /dev/ttyUSB0 | python ./post_processing_gw.py | python ./log_gw.py`
i need to execute only this string and i will have gateway?

**Comment by Arcanum7** [comment]
> You can change the log folder in log_gw.py if it is necessary

it work!

**Comment by CongducPham** [comment]
Great to know, did you also successfully flashed your STM with the Arduino_LoRa_Gateway sketch?

**Comment by Arcanum7** [comment]
> 
> 
> Great to know, did you also successfully flashed your STM with the Arduino_LoRa_Gateway sketch?

Yes, I did it - it rcv messages from my device good by CDC (usb com port).

can you  answer https://github.com/CongducPham/LowCostLoRaGw/issues/278#issuecomment-619317312

**Comment by CongducPham** [comment]
Hi, yes, normally you should have a single-channel gateway, but limited as downlink is not supported. Normally all Python scripts for cloud upload should work.

**Comment by Arcanum7** [comment]
> 
> 
> Hi, yes, normally you should have a single-channel gateway, but limited as downlink is not supported. Normally all Python scripts for cloud upload should work.

ok, uplink only by python scritps.
i close this issue, thanks!
