### ISSUE TITLE
433 case with TTN

### ISSUE THREAD

**Issue by Bekmezcii** [CongducPham/LowCostLoRaGw#286]
TTN is a great platform and your examples are based on TTN. However as I know TTN does not support 433Mhz. Can you give us a configuration example for 433 Mhz? Is there any other way to work with TTN and 433 Mhz?

**Comment by CongducPham** [comment]
Hello, I believe if you are not using OTAA or downlink, then the uplink frequency does not matter for TTN.

Otherwise, we are using ChirpStack.

regards,
