### ISSUE TITLE
Arduino Gateway

### ISSUE THREAD

**Issue by Samuel-ZDM** [CongducPham/LowCostLoRaGw#288]
Hello.

First I want to congratulate you for the great job.

I have some doubts about the arduino gateway.
My first question is whether I can use another LoRa module, RFM95, and use the same library that is being used in the code, the SX1272.
The second question is whether I can receive packages on the arduino gateway from an end-device with an LMIC code. My idea is to send to The Things Network.

Thank you very much in advance.

**Comment by CongducPham** [comment]
Hi, yes, we actually use the RFM95 module. For the second question, yes, please read https://github.com/CongducPham/LowCostLoRaGw/tree/master/Arduino#lorawan-example-and-support

regards,

**Comment by Samuel-ZDM** [comment]
Thank you.

The Arduino Gateway accepts OTAA and ABP end devices, correct?

**Comment by CongducPham** [comment]
Yes, but with some limitations with the single channel version. Read this: https://github.com/CongducPham/LowCostLoRaGw/blob/master/gw_full_latest/README-downlink.md

**Comment by Samuel-ZDM** [comment]
Thank you very much.

I'm going to do some tests. If you can't, I'll come back to ask a few more questions :). 
But his explanations helped a lot.

**Comment by Samuel-ZDM** [comment]
Hello! 
It's me again
If the gateway is like a relay gateway, will the gateway send a downlink message?

**Comment by CongducPham** [comment]
It is not really like a relay, but yes the gw can send downlink message. Did you see the related README? https://github.com/CongducPham/LowCostLoRaGw/blob/master/gw_full_latest/README-downlink.md

**Comment by Samuel-ZDM** [comment]
Thanks for your answer.

If I uncomment GW_RELAY, does the gateway just retransmit the message and the downlink doesn't work, or does it continue to work?

**Comment by CongducPham** [comment]
GW_RELAY is an experimental setting to use the gateway code to build a simple relay node. There would be no downlink then.

**Comment by Samuel-ZDM** [comment]
Ok.
Thank you.
I emailed you about a question I'm facing. Can we talk over there?
