### ISSUE TITLE
Does the ./lora_gateway supports device downlink

### ISSUE THREAD

**Issue by Unitech** [CongducPham/LowCostLoRaGw#316]
As understood in the piping sytem of the lora_gateway, you can add many adapters to broadcast data in various cloud.
But as of the nature of linux piping, data can only go in one side.

Is it possible to send event or connect to the lora_gateway in order to send custom data to a specific Lora device ?
To trigger a relay for example.

Thank you

**Comment by CongducPham** [comment]
Pipping is only used between the low-level LoRa radio and the high-level Python post-processing stage. Then Python script called from post-processing stage would take care of data upload.

What you want to do is called LoRa downlink and yes, it is possible to do this with either custom downlink (somewhat a bit simpler in design) and LoRaWAN downlink through a network server.

More info here: https://github.com/CongducPham/LowCostLoRaGw/blob/master/gw_full_latest/README-downlink.md

regards,
