### ISSUE TITLE
Data not communicated

### ISSUE THREAD

**Issue by sofibiju** [CongducPham/LowCostLoRaGw#4]
I am using Modtronix InAir9 sx1276 chip with ArduinoUNO.
I have connected pins 13 for SCK, 12 for MOSI, 11 for MISO and 2 for CS. Have connected one LoRa module with the temperature sensor and ardino as the end node. Another LoRa module with Arduino as the Gateway.

For the End node, I have uncommented the following:
#define RADIO_RFM92_95
#define BAND900

For the Gateway I have uncommented the following
#define RADIO_RFM92_95
#define BAND900
#define IS_RCV_GATEWAY

I uploaded the code into the resp. arduino and it runs fine. The End node shows Packet sent in the Arduino IDE but the data packet is not being received by the Gateway. Please suggest possible solutions.
Thank you.

**Comment by CongducPham** [comment]
Did you uncomment the line

//#define IS_RCV_GATEWAY

in the gateway code before compiling and uploading to the Arduino acting 
as gateway?

regards,

Le 16/03/16 06:23, sofibiju a écrit :
>
> I am using Modtronix InAir9 sx1276 chip with ArduinoUNO.
> I have connected pins 13 for SCK, 12 for MOSI, 11 for MISO and 2 for 
> CS. Have connected one LoRa module with the temperature sensor and 
> ardino as the end node. Another LoRa module with Arduino as the Gateway.
> The code runs fine and the End node shows Packet sent in the Arduino 
> IDE but the data packet is not being received by the Gateway. Please 
> suggest possible solutions.
> Thank you
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/CongducPham/LowCostLoRaGw/issues/4>
>

C. Pham.


-- 
|------------ Congduc PHAM - Professor --------------------------|
|  LIUPPA - Equipe T2I              |         U.P.P.A. Pau       |
|  http://liuppa.univ-pau.fr/       |   http://www.univ-pau.fr   |
|----------------------------------------------------------------|
|UPPA, LIUPPA laboratory, UFR Sciences et Techniques             |
|Avenue de l'Université - BP 1155                                |
|64013 PAU CEDEX, FRANCE                                         |
|                                                                |
|phone:  [33] (0) 5 59 40 75 94                                  |
|fax:    [33] (0) 5 59 40 76 54                                  |
|Congduc.Pham@univ-pau.fr       http://www.univ-pau.fr/~cpham    |
|----------------------------------------------------------------|

**Comment by sofibiju** [comment]
Yes I have uncommented #define IS_RCV_GATEWAY before compiling and uploading.

**Comment by sofibiju** [comment]
For the End node, I have uncommented the following:
#define RADIO_RFM92_95
#define BAND900

For the Gateway I have uncommented the following 
#define RADIO_RFM92_95
#define BAND900
#define IS_RCV_GATEWAY

**Comment by CongducPham** [comment]
Could you send me the output at the gateway side?

regards,

Le 16/03/16 08:05, sofibiju a écrit :
>
> For the End node, I have uncommented the following:
> #define RADIO_RFM92_95
> #define BAND900
>
> For the Gateway I have uncommented the following
> #define RADIO_RFM92_95
> #define BAND900
> #define IS_RCV_GATEWAY
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/CongducPham/LowCostLoRaGw/issues/4#issuecomment-197188169>
>

C. Pham.


-- 
|------------ Congduc PHAM - Professor --------------------------|
|  LIUPPA - Equipe T2I              |         U.P.P.A. Pau       |
|  http://liuppa.univ-pau.fr/       |   http://www.univ-pau.fr   |
|----------------------------------------------------------------|
|UPPA, LIUPPA laboratory, UFR Sciences et Techniques             |
|Avenue de l'Université - BP 1155                                |
|64013 PAU CEDEX, FRANCE                                         |
|                                                                |
|phone:  [33] (0) 5 59 40 75 94                                  |
|fax:    [33] (0) 5 59 40 76 54                                  |
|Congduc.Pham@univ-pau.fr       http://www.univ-pau.fr/~cpham    |
|----------------------------------------------------------------|

**Comment by sofibiju** [comment]
Gateway output
![capture](https://cloud.githubusercontent.com/assets/7882244/13807776/e909c2c6-eb88-11e5-92fb-16c1f8172194.JPG)

**Comment by CongducPham** [comment]
Seems that the gateway is in the 868MHz band, listen on channel 10, i.e. 
865.2MHz. Normally to be able to receive from your node it should be on 
channel 5 of 900MHz band, i.e. 913.88MHz.

regards,

Le 16/03/16 10:39, sofibiju a écrit :
>
> Gateway output
> capture 
> <https://cloud.githubusercontent.com/assets/7882244/13807776/e909c2c6-eb88-11e5-92fb-16c1f8172194.JPG>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/CongducPham/LowCostLoRaGw/issues/4#issuecomment-197228969>
>

C. Pham.


-- 
|------------ Congduc PHAM - Professor --------------------------|
|  LIUPPA - Equipe T2I              |         U.P.P.A. Pau       |
|  http://liuppa.univ-pau.fr/       |   http://www.univ-pau.fr   |
|----------------------------------------------------------------|
|UPPA, LIUPPA laboratory, UFR Sciences et Techniques             |
|Avenue de l'Université - BP 1155                                |
|64013 PAU CEDEX, FRANCE                                         |
|                                                                |
|phone:  [33] (0) 5 59 40 75 94                                  |
|fax:    [33] (0) 5 59 40 76 54                                  |
|Congduc.Pham@univ-pau.fr       http://www.univ-pau.fr/~cpham    |
|----------------------------------------------------------------|

**Comment by sofibiju** [comment]
I am sorry the o/p image I uploaded previously had #define BAND868 uncommented by mistake.
This is the actual image of the o/p with #define BAND900 uncommented
![capture2](https://cloud.githubusercontent.com/assets/7882244/13813123/ce02b61e-eba5-11e5-83e5-51a339ac5561.JPG)
This is the image of the end node
![temp](https://cloud.githubusercontent.com/assets/7882244/13813192/385a8000-eba6-11e5-9dd7-f51bf9145df8.JPG)
Please suggest anything else that I could try.
Thank you.

**Comment by CongducPham** [comment]
I've seen that you have very few ram memory left. That may be an issue. 

Envoyé de mon iPhone

**Comment by sofibiju** [comment]
I am using Rapsberrypi2 for gateway now and have connected the InAir9 module to gpio pins.
I have commented all lines in radio.makefile and IS_RECV_GATEWAY and BAND900 in loragateway.cpp.
I have executed the gateway and only get Sx1276 detected as output and nothing else after that. 
 
![capture](https://cloud.githubusercontent.com/assets/7882244/14038980/55ee6838-f27d-11e5-906e-57398e9f18cb.JPG)

**Comment by joehunt588** [comment]
can  you show me how you connected pin in raspi?because mine not show any output

**Comment by CongducPham** [comment]
You have to run it as root

 > sudo ./lora_gateway_pi2

Le 25/03/2016 07:16, sofibiju a écrit :
>
> I am using Rapsberrypi2 for gateway now and have connected the InAir9 
> module to gpio pins.
> I have commented all lines in radio.makefile and IS_RECV_GATEWAY and 
> BAND900 in loragateway.cpp.
> I have executed the gateway and only get Sx1276 detected as output and 
> nothing else after that.
>
> capture 
> <https://cloud.githubusercontent.com/assets/7882244/14038980/55ee6838-f27d-11e5-906e-57398e9f18cb.JPG>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/CongducPham/LowCostLoRaGw/issues/4#issuecomment-201158990>
>

C. Pham.


-- 
|------------ Congduc PHAM - Professor --------------------------|
|  LIUPPA - Equipe T2I              |         U.P.P.A. Pau       |
|  http://liuppa.univ-pau.fr/       |   http://www.univ-pau.fr   |
|----------------------------------------------------------------|
|UPPA, LIUPPA laboratory, UFR Sciences et Techniques             |
|Avenue de l'Université - BP 1155                                |
|64013 PAU CEDEX, FRANCE                                         |
|                                                                |
|phone:  [33] (0) 5 59 40 75 94                                  |
|fax:    [33] (0) 5 59 40 76 54                                  |
|Congduc.Pham@univ-pau.fr       http://www.univ-pau.fr/~cpham    |
|----------------------------------------------------------------|

**Comment by CongducPham** [comment]
OK, sorry I didn't notice that you were already in root mode. So I don't 
see immediately why it is not working. Do you still have this issue?

Le 25/03/2016 07:16, sofibiju a écrit :
>
> I am using Rapsberrypi2 for gateway now and have connected the InAir9 
> module to gpio pins.
> I have commented all lines in radio.makefile and IS_RECV_GATEWAY and 
> BAND900 in loragateway.cpp.
> I have executed the gateway and only get Sx1276 detected as output and 
> nothing else after that.
>
> capture 
> <https://cloud.githubusercontent.com/assets/7882244/14038980/55ee6838-f27d-11e5-906e-57398e9f18cb.JPG>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/CongducPham/LowCostLoRaGw/issues/4#issuecomment-201158990>
>

C. Pham.


-- 
|------------ Congduc PHAM - Professor --------------------------|
|  LIUPPA - Equipe T2I              |         U.P.P.A. Pau       |
|  http://liuppa.univ-pau.fr/       |   http://www.univ-pau.fr   |
|----------------------------------------------------------------|
|UPPA, LIUPPA laboratory, UFR Sciences et Techniques             |
|Avenue de l'Université - BP 1155                                |
|64013 PAU CEDEX, FRANCE                                         |
|                                                                |
|phone:  [33] (0) 5 59 40 75 94                                  |
|fax:    [33] (0) 5 59 40 76 54                                  |
|Congduc.Pham@univ-pau.fr       http://www.univ-pau.fr/~cpham    |
|----------------------------------------------------------------|

**Comment by sofibiju** [comment]
Yes. It is still the same

**Comment by sofibiju** [comment]
@joehunt588 joehunt588 
Raspberrypi2 connections
Connect the required SPI pins 
MISO - GPIO09 
MOSI - GPIO10 
SPI_CLK - GPIO11
SPI_nSSEL -GPIO08
VCC - 3.3V and GND to the corresponding pins on the RPI.

**Comment by sofibiju** [comment]
I have tried the gateway with an Arduino mega and now the data has been communicated successfully. So memory must have been the issue when run with Arduino Uno. Thanks for your kind support.
